# Site settings
title: The Curious Incident of Coding in the Nighttime
header-img: img/home-bg.png
email: ackerm44@gmail.com
copyright_name: ackerm44
description: > # this means to ignore newlines until "baseurl:"
  Or how I learned to stop worrying and love OO Programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ackerm44
learn_profile: ackerm44
email_username: ackerm44@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
